// <auto-generated />
using System;
using CRUDWEPAPI_EF.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUDWEPAPI_EF.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220526182458_CustomerOrderOnetoMany")]
    partial class CustomerOrderOnetoMany
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CRUDWEPAPI_EF.Model.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("CRUDWEPAPI_EF.Model.EmployeeAllowance", b =>
                {
                    b.Property<int>("employeeAllowancesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("EmployeeModelemployeeId")
                        .HasColumnType("int");

                    b.Property<string>("allowanceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("employeeId")
                        .HasColumnType("int");

                    b.HasKey("employeeAllowancesId");

                    b.HasIndex("EmployeeModelemployeeId");

                    b.ToTable("employeeAllowance");
                });

            modelBuilder.Entity("CRUDWEPAPI_EF.Model.EmployeeModel", b =>
                {
                    b.Property<int>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("employeeDept")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeeEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("promotedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("employeeId");

                    b.ToTable("employeeModel");
                });

            modelBuilder.Entity("CRUDWEPAPI_EF.Model.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("CRUDWEPAPI_EF.Model.EmployeeAllowance", b =>
                {
                    b.HasOne("CRUDWEPAPI_EF.Model.EmployeeModel", null)
                        .WithMany("employeeAllowances")
                        .HasForeignKey("EmployeeModelemployeeId");
                });

            modelBuilder.Entity("CRUDWEPAPI_EF.Model.Order", b =>
                {
                    b.HasOne("CRUDWEPAPI_EF.Model.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CRUDWEPAPI_EF.Model.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CRUDWEPAPI_EF.Model.EmployeeModel", b =>
                {
                    b.Navigation("employeeAllowances");
                });
#pragma warning restore 612, 618
        }
    }
}
